name: Pull-request actions

on:
  pull_request:
    branches:
      - master
    paths:
      - packages/address-book/**
      - '!packages/address-book/package.json'
      - '!packages/address-book/CHANGELOG.md'
      - '!packages/address-book/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/address-book
    steps:
      # get repo code
      - uses: actions/checkout@v2
      # install node
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # install packages
      - run: yarn --frozen-lockfile
      # run checksum test
      - run: yarn checksum
